services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 5

  aqa-shop:
    build: .
    ports:
      - "8080:8080"
    environment:
      # ВАЖНО: Соблюдай регистр и названия
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: pass
      # Симуляторы банков (чтобы кнопка на сайте работала)
      SPRING_CREDIT_GATE_URL: http://localhost:9999
      SPRING_PAYMENT_GATE_URL: http://localhost:9999
    depends_on:
      postgres:
        condition: service_healthy